name: .NET NuGet Tag Release
on:
  #push:
   # tags:
  #  - 'v*'
  #create:
  #  tags:
  #  - 'v*'
  push:
    branches: [ main ]

env:
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
  NUGETAPI: ${{ secrets.NUGETAPI }}      
  GH_PACKAGES_APIKEY: ${{ secrets.GH_PACKAGES_APIKEY }}
  PACKAGESAPI: ${{ secrets.PACKAGESAPI }}
  NUGETCONFIG: ${{ secrets.NUGETCONFIG }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Decode NuGet config
      run: |
        echo -n $NUGETCONFIG | base64 --decode > ./nuget.config
    - name: Push NuGets
    - shell: bash
      run: |
       for f in ./*/*.nupkg
       do
         dotnet nuget push $f -k $GH_PACKAGES_APIKEY -s $PACKAGESAPI
       done

        
